version: 2
updates:
# Create PRs for golang version updates
- package-ecosystem: docker
  directory: /
  schedule:
    interval: daily
  allowed-updates:
    - match:
        dependency-name: "golang"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
  ignore:
    - dependency-name: "golang"
      versions: ["*-rc*"]
