version = 1
SPDX-PackageName = "Gardener ingress-default-backend"
SPDX-PackageSupplier = "The Gardener project <gardener@googlegroups.com>"
SPDX-PackageDownloadLocation = "https://github.com/gardener/ingress-default-backend"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017-2024 SAP SE or an SAP affiliate company and Gardener contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017-2024 SAP SE or an SAP affiliate company and Gardener contributors"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ["public/css/**", "public/js/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2011-2016 Twitter, Inc."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "public/img/kubernetes-logo.png"
precedence = "aggregate"
SPDX-FileCopyrightText = "The Kubernetes Authors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "public/fonts/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "GLYPHICONS.com"
SPDX-License-Identifier = "CC-BY-3.0"
